import 'package:flutter/widgets.dart';

class AppStrings {
  static const List<Locale> supportedLocales = <Locale>[
    Locale('en'),
    Locale('hi'),
    Locale('ta'),
    Locale('te'),
    Locale('kn'),
    Locale('ml'),
    Locale('bn'),
  ];

  static const Map<String, String> nativeLanguageNames = {
    'en': 'English',
    'hi': 'हिंदी',
    'ta': 'தமிழ்',
    'te': 'తెలుగు',
    'kn': 'ಕನ್ನಡ',
    'ml': 'മലയാളം',
    'bn': 'বাংলা',
  };

  static const Map<String, Map<String, String>> _dict = {
    'en': {
      // common
      'cancel': 'Cancel',
      'save': 'Save',
      'retry': 'Retry',
      'close': 'Close',
      'continue': 'Continue',
      'edit': 'Edit',
      'delete': 'Delete',
      'back': 'Back',
      'loading': 'Loading...',
      'error': 'Error',
      'select': 'Select',
      'change': 'Change',
      'upload': 'Upload',
      'remove': 'Remove',
      'preview': 'Preview',
      'open': 'Open',
      'saving': 'Saving...',
      'verified': 'Verified',
      'coming_soon': 'Coming soon',
      // app
      'app_title': 'FlowFleet Partner',
      'delivery_partner': 'Delivery Partner',
      // dashboard
      'dashboard': 'Dashboard',
      'availability': 'Availability',
      'online_status': 'Online and receiving order requests',
      'offline_status': 'Offline, no new orders will be assigned',
      'kyc_warning': 'Complete KYC + bank + permissions before going online.',
      'complete': 'Complete',
      'earnings_summary': 'Earnings Summary',
      'today': 'Today',
      'this_week': 'This Week',
      'total': 'Total',
      'pending_payout': 'Pending Payout',
      'performance_metrics': 'Performance Metrics',
      'rating': 'Rating',
      'acceptance': 'Acceptance',
      'completion': 'Completion',
      'total_deliveries': 'Total Deliveries',
      'batch_pickup': 'Batch Pickup',
      'multi_order_pickup': 'Multi-Order Pickup',
      'pick_up_multiple': 'Pick up multiple orders in one trip',
      'select_orders': 'Select Orders',
      'view_trips': 'View Trips',
      'available_deliveries': 'Available Deliveries',
      'view_all': 'View All',
      'external_deliveries': 'External Deliveries',
      'external_deliveries_desc': 'View and manage deliveries from ERPNext',
      'view_deliveries': 'View Deliveries',
      'active_order': 'Active Order',
      'loading_active_order': 'Loading active order...',
      'no_active_order': 'No active order right now.',
      'browse_nearby': 'Find New Orders',
      'add_another_order': 'Add Another Order',
      'notifications': 'Notifications',
      'no_notifications': 'No notifications yet.',
      'unable_load_notifications': 'Unable to load notifications.',
      'quick_access': 'Quick Access',
      'my_profile': 'My Profile',
      'earnings_history': 'Earnings History',
      'documents': 'Documents',
      'vehicle': 'Vehicle',
      'bank_details': 'Bank Details',
      'orders_by_location': 'Orders by Location',
      'available_orders': 'New Orders',
      'external_trips': 'External Trips',
      'support': 'Support',
      'settings': 'Settings',
      'view_order': 'View Order',
      'navigate': 'Navigate',
      'open_maps': 'Open Maps',
      'track_order': 'Track Order',
      'mark_reached_pickup': 'Mark Reached Pickup',
      'mark_picked_up': 'Mark Picked Up',
      'start_delivery': 'Start Delivery',
      'mark_delivered': 'Mark Delivered',
      'mark_failed': 'Mark Failed',
      'order_delivered': 'Order delivered and earnings updated',
      'current_location': 'Current Location',
      'location_not_selected': 'Location not selected yet',
      'unable_open_maps': 'Unable to open Google Maps',
      // login
      'login': 'Login',
      'login_subtitle': 'Enter your mobile number to continue',
      'mobile_number': 'Mobile Number',
      'enter_mobile': 'Enter 10-digit mobile number',
      'send_otp': 'Send OTP',
      'sending_otp': 'Sending OTP...',
      'otp': 'OTP',
      'change_number': 'Change Number',
      'enter_otp': 'Enter OTP',
      'resend_otp': 'Resend OTP',
      'verify_login': 'Verify & Login',
      'verifying': 'Verifying...',
      // register
      'register': 'Register',
      'complete_registration': 'Complete Registration',
      'register_subtitle': 'Your mobile has been verified. Fill in your details.',
      'full_name': 'Full Name',
      'enter_full_name': 'Enter your full name',
      'email_optional': 'Email (Optional)',
      'enter_email': 'Enter your email address',
      'create_account': 'Create Account',
      'creating_account': 'Creating account...',
      'back_to_login': 'Back to Login',
      // settings
      'theme_customization': 'Theme Customization',
      'theme_mode': 'Theme Mode',
      'system': 'System',
      'light': 'Light',
      'dark': 'Dark',
      'background_color': 'Background Color',
      'accent_color': 'Accent Color',
      'language': 'Language',
      'english': 'English',
      'hindi': 'Hindi',
      'tamil': 'Tamil',
      'telugu': 'Telugu',
      'kannada': 'Kannada',
      'malayalam': 'Malayalam',
      'bengali': 'Bengali',
      'sample_english_ready': 'Ready for delivery shifts',
      'sample_hindi_ready': 'डिलीवरी शिफ्ट के लिए तैयार',
      'sample_tamil_ready': 'டெலிவரி ஷிப்ட்களுக்கு தயாராக உள்ளது',
      'sample_telugu_ready': 'డెలివరీ షిఫ్ట్‌లకు సిద్ధంగా ఉంది',
      'sample_kannada_ready': 'ಡೆಲಿವರಿ ಶಿಫ್ಟ್‌ಗಳಿಗೆ ಸಿದ್ಧವಾಗಿದೆ',
      'sample_malayalam_ready': 'ഡെലിവറി ഷിഫ്റ്റുകൾക്ക് തയ്യാറാണ്',
      'sample_bengali_ready': 'ডেলিভারি শিফটের জন্য প্রস্তুত',
      'reset_defaults': 'Reset to Defaults',
      'reset_theme_title': 'Reset Theme',
      'reset_theme_message':
          'Are you sure you want to reset all theme settings to their defaults?',
      'reset': 'Reset',
      'reset_success': 'Theme reset to defaults',
      // delivery radius
      'delivery_radius': 'Delivery Radius',
      'delivery_radius_subtitle': 'Only receive orders within this distance',
      'delivery_radius_updated': 'Delivery radius updated',
      // cod cash limit
      'cash_in_hand': 'Cash in Hand',
      'cash_limit_of': 'of',
      'cash_limit_available': 'available',
      'cash_limit_ok': 'Within limit',
      // Kept short: these render inside a pill beside the card title, and a
      // long label crowds it out (and leaves no room for longer translations).
      'cash_limit_warning': 'Near limit',
      'cash_limit_reached': 'Limit reached',
      'cash_limit_blocked_hint':
          'Settle your cash to accept more COD orders. Prepaid orders are still available.',
      'cash_limit_in_flight': 'in undelivered COD orders',
      'cash_limit_collected': 'collected',
      'cash_limit_in_order': 'in 1 order',
      'cash_limit_in_orders': 'in {count} orders',
      'cash_limit_none_held': 'You are not holding any COD cash.',
      'settle_now': 'Settle now',
      // generic errors
      'error_network': 'No internet connection. Please check your network.',
      'error_timeout': 'Request timed out. Please try again.',
      'error_unauthorized': 'Session expired. Please log in again.',
      'error_invalid_response': 'Received an invalid response from the server.',
      'error_generic': 'Something went wrong. Please try again.',
      // navigation screen
      'navigation': 'Navigation',
      'route_summary': 'Route summary',
      'no_active_route': 'No active route',
      'back_to_dashboard': 'Back to Dashboard',
      'delivery_route': 'Delivery Route',
      'pickup_store': 'Pickup store',
      'delivery_drop': 'Delivery drop',
      'open_google_maps': 'Open in Google Maps',
      'use_inapp_nav': 'Use In-app Navigation',
      'reached_pickup': 'Reached Pickup',
      // language selection
      'choose_language': 'Choose Language',
      'choose_language_subtitle': 'Select preferred app language for daily use',
      'language_info':
          'This app supports multilingual flows. You can change language again anytime from settings.',
      // profile
      'my_profile_title': 'My Profile',
      'driver_account': 'Driver account',
      'basic_information': 'Basic Information',
      'edit_profile_desc':
          'Edit name, phone number, email and profile picture',
      'name': 'Name',
      'phone_number': 'Phone Number',
      'email': 'Email',
      'save_basic_info': 'Save Basic Information',
      'no_driver_details':
          'No driver details found for this login account.',
      'driver': 'Driver',
      'no_driver_details_found': 'No driver details found for this login account.',
      'basic_details': 'Basic Details',
      'identity_and_contact_snapshot': 'Identity and contact snapshot',
      'cell_number': 'Cell Number',
      'license_details': 'License Details',
      'driving_license_and_document_info': 'Driving license and document info',
      'license_number': 'License Number',
      'issue_date': 'Issue Date',
      'expiry_date': 'Expiry Date',
      'driving_license_category': 'Driving License Category',
      'allowed_vehicle_classes': 'Allowed vehicle classes',
      'additional_driver_details': 'Additional Driver Details',
      'extra_fields_from_your_driver_doctype': 'Extra fields from your Driver doctype',
      'kyc_documents': 'KYC Documents',
      'read_only_images_from_your_url_data': 'Read-only images from your URL data',
      'no_additional_details': 'No additional details',
      'no_attachments_found': 'No attachments found',
      'opened_document': 'Opened document',
      'invalid_attachment_url': 'Invalid attachment URL',
      'unable_to_open_document': 'Unable to open document',
      'verified_account': 'Verified Account',
      'edit_name_phone_number_email_and_profile_picture': 'Edit name, phone number, email and profile picture',
      'save_basic_information': 'Save Basic Information',
      'uploading_profile_image': 'Uploading profile image...',
      'profile_image_updated': 'Profile image updated',
      'update_profile_image': 'Update Profile Image',
      'remove_profile_image': 'Remove Profile Image',
      'removing_profile_image': 'Removing profile image...',
      'profile_image_removed': 'Profile image removed',
      'upload_profile_image': 'Upload Profile Image',
      'do_you_want_to_upload_this_image': 'Do you want to upload this image?',
      'basic_information_updated': 'Basic information updated',
      'collapse': 'Collapse',
      'expand': 'Expand',
      'no_category_data': 'No category data',
      'category': 'Category',
      // order
      'order_status': 'Order Status',
      'no_active_delivery': 'No active delivery',
      'order_progress': 'Order Progress',
      'not_submitted': 'Not Submitted',
      'pending': 'Pending',
      'accepted': 'Accepted',
      'rejected': 'Rejected',
      'picked_up': 'Picked Up',
      'out_for_delivery': 'Out for Delivery',
      'delivered': 'Delivered',
      'cancelled': 'Cancelled',
      'failed': 'Failed',
      'returned': 'Returned',
      'draft': 'Draft',
      'return_trip': 'Return Trip',
      'return_trip_note': 'Return Trip for {order_name}',
      'profile_progress': 'Profile Progress',
      'profile_complete': 'Profile complete',
      'profile_completeness': 'Profile Completeness',
      'completed_steps': '{completed} of {total} completed',
      'tap_to_complete': 'Tap to complete',
      'all_done': 'All done!',
      'steps_left': '{count} steps left',
      'profile_basic_profile': 'Basic Profile',
      'profile_basic_profile_desc': 'Name, mobile and email',
      'profile_photo': 'Profile Photo',
      'profile_photo_desc': 'Add a profile photo',
      'kyc_documents_desc': 'ID proof and driving licence',
      'vehicle_details': 'Vehicle Details',
      'vehicle_details_desc': 'Register your vehicle',
      'bank_account': 'Bank Account',
      'bank_account_desc': 'Add a bank for payouts',
      'delivery_zone': 'Delivery Zone',
      'delivery_zone_desc': 'Pick your service area',
      'permissions': 'Permissions',
      'permissions_desc': 'Location and notifications',
      'ready_for_delivery_shifts': 'Ready for delivery shifts',
      'profile_complete_message':
          'Your profile is complete! You\'re ready to go online.',
      'profile_almost_complete_message':
          'Almost there! Complete your profile to unlock all features.',
      'profile_progress_message':
          'Your profile is {completed}/{total} complete. Keep going!',
      'profile_incomplete_message':
          'Complete your profile to start delivering.',
      'submitted': 'Submitted',
      'unknown': 'Unknown',
      'trips_grouped_by_driver': 'Trips grouped by driver',
      'external_delivery_trip': 'External Delivery Trip',
      'external_delivery_trips': 'External Delivery Trips',
      'delivery_failed': 'Delivery Failed',
      'confirm_failed_delivery': 'Confirm Failed Delivery',
      'add_any_additional_details': 'Add any additional details...',
    },

    // ─── HINDI ──────────────────────────────────────────────────────────────
    'hi': {
      'cancel': 'रद्द करें',
      'save': 'सहेजें',
      'retry': 'पुनः प्रयास',
      'close': 'बंद करें',
      'continue': 'जारी रखें',
      'edit': 'संपादित करें',
      'delete': 'हटाएं',
      'back': 'वापस',
      'loading': 'लोड हो रहा है...',
      'error': 'त्रुटि',
      'select': 'चुनें',
      'change': 'बदलें',
      'upload': 'अपलोड',
      'remove': 'हटाएं',
      'preview': 'पूर्वावलोकन',
      'open': 'खोलें',
      'saving': 'सहेजा जा रहा है...',
      'verified': 'सत्यापित',
      'coming_soon': 'जल्द आ रहा है',
      'app_title': 'FlowFleet पार्टनर',
      'delivery_partner': 'डिलीवरी पार्टनर',
      'dashboard': 'डैशबोर्ड',
      'availability': 'उपलब्धता',
      'online_status': 'ऑनलाइन और ऑर्डर प्राप्त कर रहे हैं',
      'offline_status': 'ऑफलाइन, कोई नया ऑर्डर नहीं मिलेगा',
      'kyc_warning': 'ऑनलाइन जाने से पहले KYC + बैंक + अनुमतियाँ पूरी करें।',
      'complete': 'पूरा करें',
      'earnings_summary': 'कमाई सारांश',
      'today': 'आज',
      'this_week': 'इस सप्ताह',
      'total': 'कुल',
      'pending_payout': 'बकाया भुगतान',
      'performance_metrics': 'प्रदर्शन मेट्रिक्स',
      'rating': 'रेटिंग',
      'acceptance': 'स्वीकृति',
      'completion': 'पूर्णता',
      'total_deliveries': 'कुल डिलीवरी',
      'batch_pickup': 'बैच पिकअप',
      'multi_order_pickup': 'मल्टी-ऑर्डर पिकअप',
      'pick_up_multiple': 'एक ट्रिप में कई ऑर्डर उठाएं',
      'select_orders': 'ऑर्डर चुनें',
      'view_trips': 'ट्रिप देखें',
      'available_deliveries': 'उपलब्ध डिलीवरी',
      'view_all': 'सभी देखें',
      'external_deliveries': 'बाहरी डिलीवरी',
      'external_deliveries_desc': 'ERPNext से डिलीवरी देखें और प्रबंधित करें',
      'view_deliveries': 'डिलीवरी देखें',
      'active_order': 'सक्रिय ऑर्डर',
      'loading_active_order': 'सक्रिय ऑर्डर लोड हो रहा है...',
      'no_active_order': 'अभी कोई सक्रिय ऑर्डर नहीं।',
      'browse_nearby': 'नए ऑर्डर खोजें',
      'add_another_order': 'दूसरा ऑर्डर जोड़ें',
      'notifications': 'सूचनाएं',
      'no_notifications': 'अभी कोई सूचना नहीं।',
      'unable_load_notifications': 'सूचनाएं लोड नहीं हो सकीं।',
      'quick_access': 'त्वरित पहुंच',
      'my_profile': 'मेरी प्रोफाइल',
      'earnings_history': 'कमाई इतिहास',
      'documents': 'दस्तावेज़',
      'vehicle': 'वाहन',
      'bank_details': 'बैंक विवरण',
      'orders_by_location': 'स्थान अनुसार ऑर्डर',
      'available_orders': 'नए ऑर्डर',
      'external_trips': 'बाहरी ट्रिप',
      'support': 'सहायता',
      'settings': 'सेटिंग्स',
      'view_order': 'ऑर्डर देखें',
      'navigate': 'नेविगेट करें',
      'open_maps': 'मैप खोलें',
      'track_order': 'ऑर्डर ट्रैक करें',
      'mark_reached_pickup': 'पिकअप पहुंचे',
      'mark_picked_up': 'उठाया गया',
      'start_delivery': 'डिलीवरी शुरू करें',
      'mark_delivered': 'डिलीवर किया',
      'order_delivered': 'ऑर्डर डिलीवर हो गया और कमाई अपडेट हुई',
      'current_location': 'वर्तमान स्थान',
      'location_not_selected': 'स्थान अभी चुना नहीं गया',
      'unable_open_maps': 'Google Maps नहीं खुल सका',
      'login': 'लॉगिन',
      'login_subtitle': 'जारी रखने के लिए मोबाइल नंबर दर्ज करें',
      'mobile_number': 'मोबाइल नंबर',
      'enter_mobile': '10 अंकों का मोबाइल नंबर दर्ज करें',
      'send_otp': 'OTP भेजें',
      'sending_otp': 'OTP भेजा जा रहा है...',
      'otp': 'OTP',
      'change_number': 'नंबर बदलें',
      'enter_otp': 'OTP दर्ज करें',
      'resend_otp': 'OTP पुनः भेजें',
      'verify_login': 'सत्यापित करें और लॉगिन करें',
      'verifying': 'सत्यापित हो रहा है...',
      'register': 'रजिस्टर',
      'complete_registration': 'पंजीकरण पूरा करें',
      'register_subtitle': 'मोबाइल सत्यापित हो गया। विवरण भरें।',
      'full_name': 'पूरा नाम',
      'enter_full_name': 'अपना पूरा नाम दर्ज करें',
      'email_optional': 'ईमेल (वैकल्पिक)',
      'enter_email': 'अपना ईमेल पता दर्ज करें',
      'create_account': 'खाता बनाएं',
      'creating_account': 'खाता बनाया जा रहा है...',
      'back_to_login': 'लॉगिन पर वापस जाएं',
      'theme_customization': 'थीम अनुकूलन',
      'theme_mode': 'थीम मोड',
      'system': 'सिस्टम',
      'light': 'लाइट',
      'dark': 'डार्क',
      'background_color': 'बैकग्राउंड रंग',
      'accent_color': 'एक्सेंट रंग',
      'language': 'भाषा',
      'english': 'अंग्रेज़ी',
      'hindi': 'हिंदी',
      'tamil': 'तमिल',
      'telugu': 'तेलुगु',
      'kannada': 'कन्नड़',
      'malayalam': 'मलयालम',
      'bengali': 'बंगाली',
      'ready_for_delivery_shifts': 'डिलीवरी शिफ्ट के लिए तैयार',
      'reset_defaults': 'डिफ़ॉल्ट पर रीसेट करें',
      'reset_theme_title': 'थीम रीसेट करें',
      'reset_theme_message':
          'क्या आप सभी थीम सेटिंग्स को डिफ़ॉल्ट पर रीसेट करना चाहते हैं?',
      'reset': 'रीसेट',
      'reset_success': 'थीम डिफ़ॉल्ट पर रीसेट हो गई',
      'navigation': 'नेविगेशन',
      'route_summary': 'रूट सारांश',
      'no_active_route': 'कोई सक्रिय रूट नहीं',
      'back_to_dashboard': 'डैशबोर्ड पर वापस जाएं',
      'delivery_route': 'डिलीवरी रूट',
      'pickup_store': 'पिकअप स्टोर',
      'delivery_drop': 'डिलीवरी ड्रॉप',
      'open_google_maps': 'Google Maps में खोलें',
      'use_inapp_nav': 'इन-ऐप नेविगेशन उपयोग करें',
      'reached_pickup': 'पिकअप पहुंच गए',
      'choose_language': 'भाषा चुनें',
      'choose_language_subtitle': 'दैनिक उपयोग के लिए पसंदीदा भाषा चुनें',
      'language_info': 'यह ऐप बहुभाषी है। सेटिंग्स से कभी भी भाषा बदल सकते हैं।',
      'my_profile_title': 'मेरी प्रोफाइल',
      'driver_account': 'ड्राइवर खाता',
      'basic_information': 'बुनियादी जानकारी',
      'edit_profile_desc': 'नाम, फोन, ईमेल और प्रोफाइल पिक्चर संपादित करें',
      'name': 'नाम',
      'phone_number': 'फ़ोन नंबर',
      'email': 'ईमेल',
      'save_basic_info': 'बुनियादी जानकारी सहेजें',
      'no_driver_details': 'इस खाते के लिए कोई ड्राइवर विवरण नहीं मिला।',
      'order_status': 'ऑर्डर स्थिति',
      'no_active_delivery': 'कोई सक्रिय डिलीवरी नहीं',
      'order_progress': 'ऑर्डर प्रगति',
      'profile_progress': 'प्रोफ़ाइल प्रगति',
      'profile_complete': 'प्रोफ़ाइल पूरी',
      'all_done': 'सब हो गया!',
      'steps_left': '{count} चरण बाकी',
      'tap_to_complete': 'पूरा करने के लिए टैप करें',
      'completed_steps': '{completed} में से {total} चरण पूरे',
      'pending': 'लंबित',
      'profile_completeness': 'प्रोफ़ाइल पूर्णता',
      'profile_basic_profile': 'बेसिक प्रोफ़ाइल',
      'profile_basic_profile_desc': 'नाम, मोबाइल और ईमेल',
      'profile_photo': 'प्रोफ़ाइल फोटो',
      'profile_photo_desc': 'प्रोफ़ाइल फोटो जोड़ें',
      'kyc_documents': 'KYC दस्तावेज़',
      'kyc_documents_desc': 'आईडी प्रूफ और ड्राइविंग लाइसेंस',
      'vehicle_details': 'वाहन विवरण',
      'vehicle_details_desc': 'अपना वाहन पंजीकृत करें',
      'bank_account': 'बैंक खाता',
      'bank_account_desc': 'भुगतान के लिए बैंक जोड़ें',
      'delivery_zone': 'डिलीवरी ज़ोन',
      'delivery_zone_desc': 'अपना कार्य क्षेत्र चुनें',
      'permissions': 'अनुमतियाँ',
      'permissions_desc': 'स्थान और सूचनाएं',
      'not_submitted': 'जमा नहीं किया गया',
      'accepted': 'स्वीकृत',
      'rejected': 'अस्वीकृत',
      'picked_up': 'पिकअप किया गया',
      'out_for_delivery': 'डिलीवरी के लिए निकला',
      'delivered': 'डिलीवर किया गया',
      'cancelled': 'रद्द',
      'failed': 'विफल',
      'returned': 'वापस किया गया',
      'draft': 'ड्राफ्ट',
      'return_trip': 'वापसी यात्रा',
      'return_trip_note': 'वापसी यात्रा: {order_name}',
      'profile_complete_message': 'आपकी प्रोफ़ाइल पूरी है! आप ऑनलाइन होने के लिए तैयार हैं।',
      'profile_almost_complete_message': 'लगभग हो गया! सभी सुविधाएं खोलने के लिए अपनी प्रोफ़ाइल पूरी करें।',
      'profile_progress_message': 'आपकी प्रोफ़ाइल {completed}/{total} पूरी है। जारी रखें!',
      'profile_incomplete_message': 'डिलीवरी शुरू करने के लिए अपनी प्रोफ़ाइल पूरी करें।',
      'submitted': 'प्रस्तुत',
      'unknown': 'अज्ञात',
      'trips_grouped_by_driver': 'ड्राइवर अनुसार ट्रिप्स',
      'external_delivery_trip': 'बाहरी डिलीवरी ट्रिप',
      'external_delivery_trips': 'बाहरी डिलीवरी ट्रिप्स',
      'delivery_failed': 'डिलीवरी विफल',
      'confirm_failed_delivery': 'विफल डिलीवरी की पुष्टि',
      'add_any_additional_details': 'कोई अतिरिक्त विवरण जोड़ें...',
    },

    // ─── TAMIL ──────────────────────────────────────────────────────────────
    'ta': {
      'cancel': 'ரத்து செய்',
      'save': 'சேமி',
      'retry': 'மீண்டும் முயற்சி',
      'close': 'மூடு',
      'continue': 'தொடரவும்',
      'edit': 'திருத்து',
      'delete': 'நீக்கு',
      'back': 'பின்செல்',
      'loading': 'ஏற்றுகிறது...',
      'error': 'பிழை',
      'select': 'தேர்ந்தெடு',
      'change': 'மாற்று',
      'upload': 'பதிவேற்று',
      'remove': 'அகற்று',
      'preview': 'முன்னோட்டம்',
      'open': 'திற',
      'saving': 'சேமிக்கிறது...',
      'verified': 'சரிபார்க்கப்பட்டது',
      'coming_soon': 'விரைவில் வருகிறது',
      'app_title': 'FlowFleet பார்ட்னர்',
      'delivery_partner': 'டெலிவரி பார்ட்னர்',
      'dashboard': 'டாஷ்போர்டு',
      'availability': 'கிடைக்கும் தன்மை',
      'online_status': 'ஆன்லைனில் உள்ளீர்கள், ஆர்டர்கள் வரும்',
      'offline_status': 'ஆஃப்லைன், புதிய ஆர்டர்கள் வராது',
      'kyc_warning': 'ஆன்லைன் ஆவதற்கு முன் KYC + வங்கி + அனுமதிகள் முடிக்கவும்.',
      'complete': 'முடிக்கவும்',
      'earnings_summary': 'வருவாய் சுருக்கம்',
      'today': 'இன்று',
      'this_week': 'இந்த வாரம்',
      'total': 'மொத்தம்',
      'pending_payout': 'நிலுவை கட்டணம்',
      'performance_metrics': 'செயல்திறன் அளவீடுகள்',
      'rating': 'மதிப்பீடு',
      'acceptance': 'ஏற்றுக்கொள்ளல்',
      'completion': 'நிறைவு',
      'total_deliveries': 'மொத்த டெலிவரிகள்',
      'batch_pickup': 'தொகுதி பிக்கப்',
      'multi_order_pickup': 'பல ஆர்டர் பிக்கப்',
      'pick_up_multiple': 'ஒரே பயணத்தில் பல ஆர்டர்கள் எடுக்கவும்',
      'select_orders': 'ஆர்டர்கள் தேர்ந்தெடு',
      'view_trips': 'பயணங்கள் பார்',
      'available_deliveries': 'கிடைக்கும் டெலிவரிகள்',
      'view_all': 'அனைத்தும் பார்',
      'external_deliveries': 'வெளிப்புற டெலிவரிகள்',
      'external_deliveries_desc': 'ERPNext இல் இருந்து டெலிவரிகள் நிர்வகிக்கவும்',
      'view_deliveries': 'டெலிவரிகள் பார்',
      'active_order': 'செயலில் உள்ள ஆர்டர்',
      'loading_active_order': 'செயலில் உள்ள ஆர்டர் ஏற்றுகிறது...',
      'no_active_order': 'தற்போது செயலில் உள்ள ஆர்டர் இல்லை.',
      'browse_nearby': 'புதிய ஆர்டர்களைக் கண்டறியவும்',
      'add_another_order': 'மற்றொரு ஆர்டர் சேர்க்கவும்',
      'notifications': 'அறிவிப்புகள்',
      'no_notifications': 'இன்னும் அறிவிப்புகள் இல்லை.',
      'unable_load_notifications': 'அறிவிப்புகளை ஏற்ற முடியவில்லை.',
      'quick_access': 'விரைவு அணுகல்',
      'my_profile': 'என் சுயவிவரம்',
      'earnings_history': 'வருவாய் வரலாறு',
      'documents': 'ஆவணங்கள்',
      'vehicle': 'வாகனம்',
      'bank_details': 'வங்கி விவரங்கள்',
      'orders_by_location': 'இடத்தின்படி ஆர்டர்கள்',
      'available_orders': 'புதிய ஆர்டர்கள்',
      'external_trips': 'வெளிப்புற பயணங்கள்',
      'support': 'ஆதரவு',
      'settings': 'அமைப்புகள்',
      'view_order': 'ஆர்டர் பார்',
      'navigate': 'வழிசெலுத்தல்',
      'open_maps': 'வரைபடம் திற',
      'track_order': 'ஆர்டர் கண்காணி',
      'mark_reached_pickup': 'பிக்கப் சென்றடைந்தோம்',
      'mark_picked_up': 'எடுத்துக்கொண்டோம்',
      'start_delivery': 'டெலிவரி தொடங்கு',
      'mark_delivered': 'டெலிவரி செய்யப்பட்டது',
      'order_delivered': 'ஆர்டர் டெலிவர், வருவாய் புதுப்பிக்கப்பட்டது',
      'current_location': 'தற்போதைய இடம்',
      'location_not_selected': 'இடம் இன்னும் தேர்ந்தெடுக்கப்படவில்லை',
      'unable_open_maps': 'Google Maps திறக்க முடியவில்லை',
      'login': 'உள்நுழை',
      'login_subtitle': 'தொடர மொபைல் எண் உள்ளிடவும்',
      'mobile_number': 'மொபைல் எண்',
      'enter_mobile': '10 இலக்க மொபைல் எண் உள்ளிடவும்',
      'send_otp': 'OTP அனுப்பு',
      'sending_otp': 'OTP அனுப்புகிறது...',
      'otp': 'OTP',
      'change_number': 'எண் மாற்று',
      'enter_otp': 'OTP உள்ளிடவும்',
      'resend_otp': 'OTP மீண்டும் அனுப்பு',
      'verify_login': 'சரிபார்த்து உள்நுழை',
      'verifying': 'சரிபார்க்கிறது...',
      'register': 'பதிவு செய்',
      'complete_registration': 'பதிவை முடிக்கவும்',
      'register_subtitle': 'மொபைல் சரிபார்க்கப்பட்டது. விவரங்களை நிரப்பவும்.',
      'full_name': 'முழு பெயர்',
      'enter_full_name': 'உங்கள் முழு பெயர் உள்ளிடவும்',
      'email_optional': 'மின்னஞ்சல் (விருப்பமானது)',
      'enter_email': 'மின்னஞ்சல் முகவரி உள்ளிடவும்',
      'create_account': 'கணக்கு உருவாக்கு',
      'creating_account': 'கணக்கு உருவாக்குகிறது...',
      'back_to_login': 'உள்நுழைவுக்கு திரும்பு',
      'theme_customization': 'தீம் தனிப்பயனாக்கம்',
      'theme_mode': 'தீம் முறை',
      'system': 'கணினி',
      'light': 'ஒளி',
      'dark': 'இருள்',
      'background_color': 'பின்னணி நிறம்',
      'accent_color': 'அக்சென்ட் நிறம்',
      'language': 'மொழி',
      'english': 'ஆங்கிலம்',
      'hindi': 'இந்தி',
      'tamil': 'தமிழ்',
      'telugu': 'தெலుగు',
      'kannada': 'கன்னடம்',
      'malayalam': 'மலையாளம்',
      'bengali': 'பெங்காலி',
      'ready_for_delivery_shifts': 'டெலிவரி ஷிப்ட்களுக்கு தயாராக உள்ளது',
      'reset_defaults': 'இயல்புநிலைக்கு மீட்டமை',
      'reset_theme_title': 'தீம் மீட்டமை',
      'reset_theme_message': 'அனைத்து தீம் அமைப்புகளையும் இயல்புநிலைக்கு மீட்டமைக்கவா?',
      'reset': 'மீட்டமை',
      'reset_success': 'தீம் இயல்புநிலைக்கு மீட்டமைக்கப்பட்டது',
      'navigation': 'வழிசெலுத்தல்',
      'route_summary': 'வழி சுருக்கம்',
      'no_active_route': 'செயலில் உள்ள வழி இல்லை',
      'back_to_dashboard': 'டாஷ்போர்டுக்கு திரும்பு',
      'delivery_route': 'டெலிவரி வழி',
      'pickup_store': 'பிக்கப் கடை',
      'delivery_drop': 'டெலிவரி இடம்',
      'open_google_maps': 'Google Maps இல் திற',
      'use_inapp_nav': 'ஆப் வழிசெலுத்தல் பயன்படுத்து',
      'reached_pickup': 'பிக்கப் சென்றடைந்தோம்',
      'choose_language': 'மொழி தேர்ந்தெடு',
      'choose_language_subtitle': 'தினசரி பயன்பாட்டிற்கான மொழியை தேர்ந்தெடு',
      'language_info': 'இந்த ஆப் பல மொழிகளை ஆதரிக்கிறது. அமைப்புகளில் எப்போதும் மொழி மாற்றலாம்.',
      'my_profile_title': 'என் சுயவிவரம்',
      'driver_account': 'டிரைவர் கணக்கு',
      'basic_information': 'அடிப்படை தகவல்',
      'edit_profile_desc': 'பெயர், தொலைபேசி, மின்னஞ்சல் மற்றும் படம் திருத்து',
      'name': 'பெயர்',
      'phone_number': 'தொலைபேசி எண்',
      'email': 'மின்னஞ்சல்',
      'save_basic_info': 'அடிப்படை தகவல் சேமி',
      'no_driver_details': 'இந்த கணக்கிற்கு டிரைவர் விவரங்கள் இல்லை.',
      'order_status': 'ஆர்டர் நிலை',
      'no_active_delivery': 'செயலில் உள்ள டெலிவரி இல்லை',
      'order_progress': 'ஆர்டர் முன்னேற்றம்',
      'profile_progress': 'சுயவிவர முன்னேற்றம்',
      'profile_complete': 'சுயவிவரம் முழுமை',
      'all_done': 'அனைத்தும் முடிந்தது!',
      'steps_left': '{count} படிகள் மீதம்',
      'tap_to_complete': 'முடிக்க தொடவும்',
      'completed_steps': '{completed} / {total} படிகள் முடிந்தன',
      'pending': 'நிலுவையில்',
      'profile_completeness': 'சுயவிவர முழுமை',
      'profile_basic_profile': 'அடிப்படை சுயவிவரம்',
      'profile_basic_profile_desc': 'பெயர், மொபைல் & மின்னஞ்சல்',
      'profile_photo': 'சுயவிவர புகைப்படம்',
      'profile_photo_desc': 'சுயவிவர புகைப்படம் சேர்க்கவும்',
      'kyc_documents': 'KYC ஆவணங்கள்',
      'kyc_documents_desc': 'அடையாள சான்று & ஓட்டுநர் உரிமம்',
      'vehicle_details': 'வாகன விவரங்கள்',
      'vehicle_details_desc': 'உங்கள் வாகனத்தை பதிவு செய்யவும்',
      'bank_account': 'வங்கி கணக்கு',
      'bank_account_desc': 'பணப்பரிவர்த்தனைக்கு வங்கி சேர்க்கவும்',
      'delivery_zone': 'டெலிவரி பகுதி',
      'delivery_zone_desc': 'உங்கள் வேலை பகுதியை தேர்வு செய்யவும்',
      'permissions': 'அனுமதிகள்',
      'permissions_desc': 'இடம் & அறிவிப்புகள்',
      'not_submitted': 'சமர்ப்பிக்கப்படவில்லை',
      'accepted': 'ஏற்றுக்கொள்ளப்பட்டது',
      'rejected': 'நிராகரிக்கப்பட்டது',
      'picked_up': 'எடுத்துக்கொள்ளப்பட்டது',
      'out_for_delivery': 'டெலிவரிக்குப் புறப்பட்டது',
      'delivered': 'டெலிவரி செய்யப்பட்டது',
      'cancelled': 'ரத்து செய்யப்பட்டது',
      'failed': 'தோல்வி',
      'returned': 'திரும்பப் பெறப்பட்டது',
      'draft': 'வரைவு',
      'return_trip': 'திரும்பும் பயணம்',
      'return_trip_note': 'திரும்பும் பயணம்: {order_name}',
      'profile_complete_message': 'உங்கள் சுயவிவரம் முழுமை! ஆன்லைனில் செல்ல தயாராக உள்ளீர்கள்.',
      'profile_almost_complete_message': 'கிட்டத்தட்ட முடிந்தது! அனைத்து அம்சங்களையும் திறக்க உங்கள் சுயவிவரத்தை முடிக்கவும்.',
      'profile_progress_message': 'உங்கள் சுயவிவரம் {completed}/{total} முடிந்துள்ளது. தொடரவும்!',
      'profile_incomplete_message': 'டெலிவரி தொடங்க உங்கள் சுயவிவரத்தை முடிக்கவும்.',
      'submitted': 'சமர்ப்பிக்கப்பட்டது',
      'unknown': 'தெரியவில்லை',
      'trips_grouped_by_driver': 'டிரைவர் வாரியான பயணங்கள்',
      'external_delivery_trip': 'வெளிப்புற டெலிவரி பயணம்',
      'external_delivery_trips': 'வெளிப்புற டெலிவரி பயணங்கள்',
      'delivery_failed': 'டெலிவரி தோல்வி',
      'confirm_failed_delivery': 'தோல்வியடைந்த டெலிவரியை உறுதிப்படுத்தவும்',
      'add_any_additional_details': 'கூடுதல் விவரங்களைச் சேர்க்கவும்...',
    },

    // ─── TELUGU ─────────────────────────────────────────────────────────────
    'te': {
      'cancel': 'రద్దు చేయి',
      'save': 'సేవ్ చేయి',
      'retry': 'మళ్ళీ ప్రయత్నించు',
      'close': 'మూసివేయి',
      'continue': 'కొనసాగించు',
      'edit': 'సవరించు',
      'delete': 'తొలగించు',
      'back': 'వెనక్కు',
      'loading': 'లోడ్ అవుతోంది...',
      'error': 'లోపం',
      'select': 'ఎంచుకో',
      'change': 'మార్చు',
      'upload': 'అప్‌లోడ్ చేయి',
      'remove': 'తొలగించు',
      'preview': 'ముందు చూపు',
      'open': 'తెరువు',
      'saving': 'సేవ్ అవుతోంది...',
      'verified': 'ధృవీకరించబడింది',
      'coming_soon': 'త్వరలో వస్తుంది',
      'app_title': 'FlowFleet పార్టనర్',
      'delivery_partner': 'డెలివరీ పార్టనర్',
      'dashboard': 'డాష్‌బోర్డ్',
      'availability': 'లభ్యత',
      'online_status': 'ఆన్‌లైన్‌లో ఉన్నారు, ఆర్డర్లు వస్తున్నాయి',
      'offline_status': 'ఆఫ్‌లైన్, కొత్త ఆర్డర్లు రావు',
      'kyc_warning': 'ఆన్‌లైన్ అవ్వడానికి ముందు KYC + బ్యాంక్ + అనుమతులు పూర్తి చేయండి.',
      'complete': 'పూర్తి చేయి',
      'earnings_summary': 'ఆదాయ సారాంశం',
      'today': 'ఈరోజు',
      'this_week': 'ఈ వారం',
      'total': 'మొత్తం',
      'pending_payout': 'పెండింగ్ చెల్లింపు',
      'performance_metrics': 'పనితీరు కొలమానాలు',
      'rating': 'రేటింగ్',
      'acceptance': 'అంగీకారం',
      'completion': 'పూర్తి',
      'total_deliveries': 'మొత్తం డెలివరీలు',
      'batch_pickup': 'బ్యాచ్ పికప్',
      'multi_order_pickup': 'మల్టీ-ఆర్డర్ పికప్',
      'pick_up_multiple': 'ఒక ట్రిప్‌లో బహుళ ఆర్డర్లు తీసుకో',
      'select_orders': 'ఆర్డర్లు ఎంచుకో',
      'view_trips': 'ట్రిప్‌లు చూడు',
      'available_deliveries': 'అందుబాటులో ఉన్న డెలివరీలు',
      'view_all': 'అన్నీ చూడు',
      'external_deliveries': 'బాహ్య డెలివరీలు',
      'external_deliveries_desc': 'ERPNext నుండి డెలివరీలు నిర్వహించండి',
      'view_deliveries': 'డెలివరీలు చూడు',
      'active_order': 'చురుకైన ఆర్డర్',
      'loading_active_order': 'చురుకైన ఆర్డర్ లోడ్ అవుతోంది...',
      'no_active_order': 'ప్రస్తుతం చురుకైన ఆర్డర్ లేదు.',
      'browse_nearby': 'కొత్త ఆర్డర్లను కనుగొనండి',
      'add_another_order': 'మరొక ఆర్డర్ జోడించు',
      'notifications': 'నోటిఫికేషన్లు',
      'no_notifications': 'ఇంకా నోటిఫికేషన్లు లేవు.',
      'unable_load_notifications': 'నోటిఫికేషన్లు లోడ్ చేయలేకపోయాం.',
      'quick_access': 'త్వరిత యాక్సెస్',
      'my_profile': 'నా ప్రొఫైల్',
      'earnings_history': 'ఆదాయ చరిత్ర',
      'documents': 'పత్రాలు',
      'vehicle': 'వాహనం',
      'bank_details': 'బ్యాంక్ వివరాలు',
      'orders_by_location': 'స్థానం వారీగా ఆర్డర్లు',
      'available_orders': 'కొత్త ఆర్డర్లు',
      'external_trips': 'బాహ్య ట్రిప్‌లు',
      'support': 'మద్దతు',
      'settings': 'సెట్టింగులు',
      'view_order': 'ఆర్డర్ చూడు',
      'navigate': 'నేవిగేట్ చేయి',
      'open_maps': 'మ్యాప్ తెరువు',
      'track_order': 'ఆర్డర్ ట్రాక్ చేయి',
      'mark_reached_pickup': 'పికప్ చేరుకున్నాము',
      'mark_picked_up': 'తీసుకున్నాము',
      'start_delivery': 'డెలివరీ మొదలుపెట్టు',
      'mark_delivered': 'డెలివర్ చేయబడింది',
      'order_delivered': 'ఆర్డర్ డెలివర్ అయింది, ఆదాయం అప్‌డేట్ అయింది',
      'current_location': 'ప్రస్తుత స్థానం',
      'location_not_selected': 'స్థానం ఇంకా ఎంచుకోలేదు',
      'unable_open_maps': 'Google Maps తెరవడం సాధ్యం కాలేదు',
      'login': 'లాగిన్',
      'login_subtitle': 'కొనసాగించడానికి మొబైల్ నంబర్ నమోదు చేయండి',
      'mobile_number': 'మొబైల్ నంబర్',
      'enter_mobile': '10 అంకెల మొబైల్ నంబర్ నమోదు చేయండి',
      'send_otp': 'OTP పంపు',
      'sending_otp': 'OTP పంపుతోంది...',
      'otp': 'OTP',
      'change_number': 'నంబర్ మార్చు',
      'enter_otp': 'OTP నమోదు చేయండి',
      'resend_otp': 'OTP మళ్ళీ పంపు',
      'verify_login': 'ధృవీకరించి లాగిన్ చేయి',
      'verifying': 'ధృవీకరిస్తోంది...',
      'register': 'నమోదు చేసుకో',
      'complete_registration': 'నమోదు పూర్తి చేయి',
      'register_subtitle': 'మొబైల్ ధృవీకరించబడింది. వివరాలు నమోదు చేయండి.',
      'full_name': 'పూర్తి పేరు',
      'enter_full_name': 'మీ పూర్తి పేరు నమోదు చేయండి',
      'email_optional': 'ఇమెయిల్ (ఐచ్ఛికం)',
      'enter_email': 'ఇమెయిల్ చిరునామా నమోదు చేయండి',
      'create_account': 'ఖాతా సృష్టించు',
      'creating_account': 'ఖాతా సృష్టిస్తోంది...',
      'back_to_login': 'లాగిన్‌కు తిరిగి వెళ్ళు',
      'theme_customization': 'థీమ్ అనుకూలీకరణ',
      'theme_mode': 'థీమ్ మోడ్',
      'system': 'సిస్టమ్',
      'light': 'లైట్',
      'dark': 'డార్క్',
      'background_color': 'నేపథ్య రంగు',
      'accent_color': 'యాక్సెంట్ రంగు',
      'language': 'భాష',
      'english': 'ఇంగ్లీష్',
      'hindi': 'హిందీ',
      'tamil': 'తమిళం',
      'telugu': 'తెలుగు',
      'kannada': 'ಕನ್ನಡ',
      'malayalam': 'മലയാളം',
      'bengali': 'బెంగాలీ',
      'ready_for_delivery_shifts': 'డెలివరీ షిఫ్ట్‌లకు సిద్ధంగా ఉంది',
      'reset_defaults': 'డిఫాల్ట్‌కు రీసెట్ చేయి',
      'reset_theme_title': 'థీమ్ రీసెట్',
      'reset_theme_message': 'అన్ని థీమ్ సెట్టింగులను డిఫాల్ట్‌కు రీసెట్ చేయాలా?',
      'reset': 'రీసెట్',
      'reset_success': 'థీమ్ డిఫాల్ట్‌కు రీసెట్ అయింది',
      'navigation': 'నేవిగేషన్',
      'route_summary': 'రూట్ సారాంశం',
      'no_active_route': 'చురుకైన రూట్ లేదు',
      'back_to_dashboard': 'డాష్‌బోర్డ్‌కు తిరిగి వెళ్ళు',
      'delivery_route': 'డెలివరీ రూట్',
      'pickup_store': 'పికప్ స్టోర్',
      'delivery_drop': 'డెలివరీ డ్రాప్',
      'open_google_maps': 'Google Maps లో తెరువు',
      'use_inapp_nav': 'ఇన్-యాప్ నేవిగేషన్ ఉపయోగించు',
      'reached_pickup': 'పికప్ చేరుకున్నాము',
      'choose_language': 'భాష ఎంచుకో',
      'choose_language_subtitle': 'రోజువారీ వినియోగానికి భాష ఎంచుకో',
      'language_info': 'ఈ యాప్ బహుభాష మద్దతు ఇస్తుంది. సెట్టింగులలో ఎప్పుడైనా మార్చవచ్చు.',
      'my_profile_title': 'నా ప్రొఫైల్',
      'driver_account': 'డ్రైవర్ ఖాతా',
      'basic_information': 'ప్రాథమిక సమాచారం',
      'edit_profile_desc': 'పేరు, ఫోన్, ఇమెయిల్ మరియు ప్రొఫైల్ చిత్రాన్ని సవరించండి',
      'name': 'పేరు',
      'phone_number': 'ఫోన్ నంబర్',
      'email': 'ఇమెయిల్',
      'save_basic_info': 'ప్రాథమిక సమాచారం సేవ్ చేయి',
      'no_driver_details': 'ఈ ఖాతాకు డ్రైవర్ వివరాలు కనుగొనబడలేదు.',
      'order_status': 'ఆర్డర్ స్థితి',
      'no_active_delivery': 'చురుకైన డెలివరీ లేదు',
      'order_progress': 'ఆర్డర్ పురోగతి',
      'profile_progress': 'ప్రొఫైల్ పురోగతి',
      'profile_complete': 'ప్రొఫైల్ పూర్తైంది',
      'all_done': 'అన్నీ పూర్తయ్యాయి!',
      'steps_left': '{count} దశలు మిగిలాయి',
      'tap_to_complete': 'పూర్తి చేయడానికి ట్యాప్ చేయండి',
      'completed_steps': '{completed} లో {total} దశలు పూర్తయ్యాయి',
      'pending': 'పెండింగ్',
      'profile_completeness': 'ప్రొఫైల్ పూర్తి స్థాయి',
      'profile_basic_profile': 'ప్రాథమిక ప్రొఫైల్',
      'profile_basic_profile_desc': 'పేరు, మొబైల్ & ఇమెయిల్',
      'profile_photo': 'ప్రొఫైల్ ఫోటో',
      'profile_photo_desc': 'ప్రొఫైల్ ఫోటో జోడించండి',
      'kyc_documents': 'KYC పత్రాలు',
      'kyc_documents_desc': 'ఐడి ప్రూఫ్ & డ్రైవింగ్ లైసెన్స్',
      'vehicle_details': 'వాహన వివరాలు',
      'vehicle_details_desc': 'మీ వాహనాన్ని నమోదు చేయండి',
      'bank_account': 'బ్యాంక్ ఖాతా',
      'bank_account_desc': 'చెల్లింపుల కోసం బ్యాంక్ జోడించండి',
      'delivery_zone': 'డెలివరీ జోన్',
      'delivery_zone_desc': 'మీ పని ప్రాంతాన్ని ఎంచుకోండి',
      'permissions': 'అనుమతులు',
      'permissions_desc': 'స్థానం & నోటిఫికేషన్లు',
      'not_submitted': 'సమర్పించలేదు',
      'accepted': 'అంగీకరించబడింది',
      'rejected': 'తిరస్కరించబడింది',
      'picked_up': 'తీసుకున్నారు',
      'out_for_delivery': 'డెలివరీకి బయలుదేరింది',
      'delivered': 'డెలివరీ అయింది',
      'cancelled': 'రద్దు చేయబడింది',
      'failed': 'విఫలం',
      'returned': 'తిరిగి ఇవ్వబడింది',
      'draft': 'డ్రాఫ్ట్',
      'return_trip': 'రిటర్న్ ట్రిప్',
      'return_trip_note': 'రిటర్న్ ట్రిప్: {order_name}',
      'profile_complete_message': 'మీ ప్రొఫైల్ పూర్తైంది! మీరు ఆన్‌లైన్‌కి సిద్ధంగా ఉన్నారు.',
      'profile_almost_complete_message': 'దాదాపు పూర్తైంది! అన్ని ఫీచర్లను అన్‌లాక్ చేయడానికి మీ ప్రొఫైల్‌ని పూర్తి చేయండి.',
      'profile_progress_message': 'మీ ప్రొఫైల్ {completed}/{total} పూర్తైంది. కొనసాగించండి!',
      'profile_incomplete_message': 'డెలివరీ ప్రారంభించడానికి మీ ప్రొఫైల్‌ని పూర్తి చేయండి.',
      'submitted': 'సమర్పించబడింది',
      'unknown': 'తెలియదు',
      'trips_grouped_by_driver': 'డ్రైవర్ వారీగా ట్రిప్‌లు',
      'external_delivery_trip': 'బాహ్య డెలివరీ ట్రిప్',
      'external_delivery_trips': 'బాహ్య డెలివరీ ట్రిప్స్',
      'delivery_failed': 'డెలివరీ విఫలమైంది',
      'confirm_failed_delivery': 'విఫలమైన డెలివరీని నిర్ధారించండి',
      'add_any_additional_details': 'అదనపు వివరాలను జోడించండి...',
    },

    // ─── KANNADA ────────────────────────────────────────────────────────────
    'kn': {
      'cancel': 'ರದ್ದು ಮಾಡಿ',
      'save': 'ಉಳಿಸಿ',
      'retry': 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
      'close': 'ಮುಚ್ಚಿ',
      'continue': 'ಮುಂದುವರಿಸಿ',
      'edit': 'ತಿದ್ದಿರಿ',
      'delete': 'ಅಳಿಸಿ',
      'back': 'ಹಿಂದೆ',
      'loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
      'error': 'ದೋಷ',
      'select': 'ಆಯ್ಕೆ ಮಾಡಿ',
      'change': 'ಬದಲಾಯಿಸಿ',
      'upload': 'ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
      'remove': 'ತೆಗೆದುಹಾಕಿ',
      'preview': 'ಮೊದಲು ನೋಡಿ',
      'open': 'ತೆರೆಯಿರಿ',
      'saving': 'ಉಳಿಸಲಾಗುತ್ತಿದೆ...',
      'verified': 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
      'coming_soon': 'ಶೀಘ್ರದಲ್ಲಿ ಬರುತ್ತದೆ',
      'app_title': 'FlowFleet ಪಾರ್ಟ್ನರ್',
      'delivery_partner': 'ಡೆಲಿವರಿ ಪಾರ್ಟ್ನರ್',
      'dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
      'availability': 'ಲಭ್ಯತೆ',
      'online_status': 'ಆನ್‌ಲೈನ್‌ನಲ್ಲಿದ್ದೀರಿ, ಆರ್ಡರ್‌ಗಳು ಬರುತ್ತಿವೆ',
      'offline_status': 'ಆಫ್‌ಲೈನ್, ಹೊಸ ಆರ್ಡರ್‌ಗಳು ಬರುವುದಿಲ್ಲ',
      'kyc_warning': 'ಆನ್‌ಲೈನ್ ಆಗುವ ಮೊದಲು KYC + ಬ್ಯಾಂಕ್ + ಅನುಮತಿಗಳನ್ನು ಪೂರ್ಣಗೊಳಿಸಿ.',
      'complete': 'ಪೂರ್ಣಗೊಳಿಸಿ',
      'earnings_summary': 'ಆದಾಯ ಸಾರಾಂಶ',
      'today': 'ಇಂದು',
      'this_week': 'ಈ ವಾರ',
      'total': 'ಒಟ್ಟು',
      'pending_payout': 'ಬಾಕಿ ಪಾವತಿ',
      'performance_metrics': 'ಕಾರ್ಯಕ್ಷಮತೆ ಅಳತೆಗಳು',
      'rating': 'ರೇಟಿಂಗ್',
      'acceptance': 'ಒಪ್ಪಿಗೆ',
      'completion': 'ಪೂರ್ಣತೆ',
      'total_deliveries': 'ಒಟ್ಟು ಡೆಲಿವರಿಗಳು',
      'batch_pickup': 'ಬ್ಯಾಚ್ ಪಿಕಪ್',
      'multi_order_pickup': 'ಮಲ್ಟಿ-ಆರ್ಡರ್ ಪಿಕಪ್',
      'pick_up_multiple': 'ಒಂದು ಪ್ರಯಾಣದಲ್ಲಿ ಹಲವು ಆರ್ಡರ್‌ಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳಿ',
      'select_orders': 'ಆರ್ಡರ್‌ಗಳನ್ನು ಆಯ್ಕೆ ಮಾಡಿ',
      'view_trips': 'ಪ್ರಯಾಣಗಳನ್ನು ನೋಡಿ',
      'available_deliveries': 'ಲಭ್ಯ ಡೆಲಿವರಿಗಳು',
      'view_all': 'ಎಲ್ಲಾ ನೋಡಿ',
      'external_deliveries': 'ಬಾಹ್ಯ ಡೆಲಿವರಿಗಳು',
      'external_deliveries_desc': 'ERPNext ನಿಂದ ಡೆಲಿವರಿಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
      'view_deliveries': 'ಡೆಲಿವರಿಗಳನ್ನು ನೋಡಿ',
      'active_order': 'ಸಕ್ರಿಯ ಆರ್ಡರ್',
      'loading_active_order': 'ಸಕ್ರಿಯ ಆರ್ಡರ್ ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
      'no_active_order': 'ಈಗ ಯಾವುದೇ ಸಕ್ರಿಯ ಆರ್ಡರ್ ಇಲ್ಲ.',
      'browse_nearby': 'ಹೊಸ ಆರ್ಡರ್‌ಗಳನ್ನು ಹುಡುಕಿ',
      'add_another_order': 'ಮತ್ತೊಂದು ಆರ್ಡರ್ ಸೇರಿಸಿ',
      'notifications': 'ಅಧಿಸೂಚನೆಗಳು',
      'no_notifications': 'ಇನ್ನೂ ಯಾವುದೇ ಅಧಿಸೂಚನೆಗಳಿಲ್ಲ.',
      'unable_load_notifications': 'ಅಧಿಸೂಚನೆಗಳನ್ನು ಲೋಡ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.',
      'quick_access': 'ತ್ವರಿತ ಪ್ರವೇಶ',
      'my_profile': 'ನನ್ನ ಪ್ರೊಫೈಲ್',
      'earnings_history': 'ಆದಾಯ ಇತಿಹಾಸ',
      'documents': 'ದಾಖಲೆಗಳು',
      'vehicle': 'ವಾಹನ',
      'bank_details': 'ಬ್ಯಾಂಕ್ ವಿವರಗಳು',
      'orders_by_location': 'ಸ್ಥಳದ ಪ್ರಕಾರ ಆರ್ಡರ್‌ಗಳು',
      'available_orders': 'ಹೊಸ ಆರ್ಡರ್‌ಗಳು',
      'external_trips': 'ಬಾಹ್ಯ ಪ್ರಯಾಣಗಳು',
      'support': 'ಬೆಂಬಲ',
      'settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
      'view_order': 'ಆರ್ಡರ್ ನೋಡಿ',
      'navigate': 'ನ್ಯಾವಿಗೇಟ್ ಮಾಡಿ',
      'open_maps': 'ನಕ್ಷೆ ತೆರೆಯಿರಿ',
      'track_order': 'ಆರ್ಡರ್ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
      'mark_reached_pickup': 'ಪಿಕಪ್‌ಗೆ ತಲುಪಿದ್ದೇವೆ',
      'mark_picked_up': 'ತೆಗೆದುಕೊಂಡಿದ್ದೇವೆ',
      'start_delivery': 'ಡೆಲಿವರಿ ಪ್ರಾರಂಭಿಸಿ',
      'mark_delivered': 'ಡೆಲಿವರ್ ಆಯಿತು',
      'order_delivered': 'ಆರ್ಡರ್ ಡೆಲಿವರ್ ಆಯಿತು, ಆದಾಯ ಅಪ್‌ಡೇಟ್ ಆಗಿದೆ',
      'current_location': 'ಪ್ರಸ್ತುತ ಸ್ಥಳ',
      'location_not_selected': 'ಇನ್ನೂ ಸ್ಥಳ ಆಯ್ಕೆ ಮಾಡಿಲ್ಲ',
      'unable_open_maps': 'Google Maps ತೆರೆಯಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ',
      'login': 'ಲಾಗಿನ್',
      'login_subtitle': 'ಮುಂದುವರಿಯಲು ಮೊಬೈಲ್ ನಂಬರ್ ನಮೂದಿಸಿ',
      'mobile_number': 'ಮೊಬೈಲ್ ನಂಬರ್',
      'enter_mobile': '10 ಅಂಕಿಯ ಮೊಬೈಲ್ ನಂಬರ್ ನಮೂದಿಸಿ',
      'send_otp': 'OTP ಕಳುಹಿಸಿ',
      'sending_otp': 'OTP ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ...',
      'otp': 'OTP',
      'change_number': 'ನಂಬರ್ ಬದಲಾಯಿಸಿ',
      'enter_otp': 'OTP ನಮೂದಿಸಿ',
      'resend_otp': 'OTP ಮತ್ತೆ ಕಳುಹಿಸಿ',
      'verify_login': 'ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಲಾಗಿನ್ ಮಾಡಿ',
      'verifying': 'ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...',
      'register': 'ನೋಂದಾಯಿಸಿ',
      'complete_registration': 'ನೋಂದಣಿ ಪೂರ್ಣಗೊಳಿಸಿ',
      'register_subtitle': 'ಮೊಬೈಲ್ ಪರಿಶೀಲಿಸಲಾಗಿದೆ. ವಿವರಗಳನ್ನು ಭರ್ತಿ ಮಾಡಿ.',
      'full_name': 'ಪೂರ್ಣ ಹೆಸರು',
      'enter_full_name': 'ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರನ್ನು ನಮೂದಿಸಿ',
      'email_optional': 'ಇಮೇಲ್ (ಐಚ್ಛಿಕ)',
      'enter_email': 'ಇಮೇಲ್ ವಿಳಾಸ ನಮೂದಿಸಿ',
      'create_account': 'ಖಾತೆ ರಚಿಸಿ',
      'creating_account': 'ಖಾತೆ ರಚಿಸಲಾಗುತ್ತಿದೆ...',
      'back_to_login': 'ಲಾಗಿನ್‌ಗೆ ಹಿಂದೆ ಹೋಗಿ',
      'theme_customization': 'ಥೀಮ್ ಕಸ್ಟಮೈಸೇಶನ್',
      'theme_mode': 'ಥೀಮ್ ಮೋಡ್',
      'system': 'ಸಿಸ್ಟಮ್',
      'light': 'ಲೈಟ್',
      'dark': 'ಡಾರ್ಕ್',
      'background_color': 'ಹಿನ್ನೆಲೆ ಬಣ್ಣ',
      'accent_color': 'ಆಕ್ಸೆಂಟ್ ಬಣ್ಣ',
      'language': 'ಭಾಷೆ',
      'english': 'ಇಂಗ್ಲಿಷ್',
      'hindi': 'ಹಿಂದಿ',
      'tamil': 'ತಮಿಳು',
      'telugu': 'ತೆಲುಗು',
      'kannada': 'ಕನ್ನಡ',
      'malayalam': 'ಮಲಯಾಳಂ',
      'bengali': 'ಬೆಂಗಾಳಿ',
      'ready_for_delivery_shifts': 'ಡೆಲಿವರಿ ಶಿಫ್ಟ್‌ಗಳಿಗೆ ಸಿದ್ಧವಾಗಿದೆ',
      'reset_defaults': 'ಡಿಫಾಲ್ಟ್‌ಗೆ ಮರುಹೊಂದಿಸಿ',
      'reset_theme_title': 'ಥೀಮ್ ಮರುಹೊಂದಿಸಿ',
      'reset_theme_message': 'ಎಲ್ಲಾ ಥೀಮ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳನ್ನು ಡಿಫಾಲ್ಟ್‌ಗೆ ಮರುಹೊಂದಿಸಲೇ?',
      'reset': 'ಮರುಹೊಂದಿಸಿ',
      'reset_success': 'ಥೀಮ್ ಡಿಫಾಲ್ಟ್‌ಗೆ ಮರುಹೊಂದಿಸಲಾಗಿದೆ',
      'navigation': 'ನ್ಯಾವಿಗೇಶನ್',
      'route_summary': 'ರೂಟ್ ಸಾರಾಂಶ',
      'no_active_route': 'ಯಾವುದೇ ಸಕ್ರಿಯ ರೂಟ್ ಇಲ್ಲ',
      'back_to_dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹಿಂದೆ ಹೋಗಿ',
      'delivery_route': 'ಡೆಲಿವರಿ ರೂಟ್',
      'pickup_store': 'ಪಿಕಪ್ ಸ್ಟೋರ್',
      'delivery_drop': 'ಡೆಲಿವರಿ ಡ್ರಾಪ್',
      'open_google_maps': 'Google Maps ನಲ್ಲಿ ತೆರೆಯಿರಿ',
      'use_inapp_nav': 'ಇನ್-ಆ್ಯಪ್ ನ್ಯಾವಿಗೇಶನ್ ಬಳಸಿ',
      'reached_pickup': 'ಪಿಕಪ್‌ಗೆ ತಲುಪಿದ್ದೇವೆ',
      'choose_language': 'ಭಾಷೆ ಆಯ್ಕೆ ಮಾಡಿ',
      'choose_language_subtitle': 'ದೈನಂದಿನ ಬಳಕೆಗೆ ಆದ್ಯತೆಯ ಭಾಷೆ ಆಯ್ಕೆ ಮಾಡಿ',
      'language_info': 'ಈ ಆ್ಯಪ್ ಬಹುಭಾಷಾ ಬೆಂಬಲ ಹೊಂದಿದೆ. ಸೆಟ್ಟಿಂಗ್‌ಗಳಲ್ಲಿ ಯಾವಾಗಲೂ ಭಾಷೆ ಬದಲಾಯಿಸಬಹುದು.',
      'my_profile_title': 'ನನ್ನ ಪ್ರೊಫೈಲ್',
      'driver_account': 'ಚಾಲಕ ಖಾತೆ',
      'basic_information': 'ಮೂಲ ಮಾಹಿತಿ',
      'edit_profile_desc': 'ಹೆಸರು, ಫೋನ್, ಇಮೇಲ್ ಮತ್ತು ಪ್ರೊಫೈಲ್ ಚಿತ್ರ ತಿದ್ದಿರಿ',
      'name': 'ಹೆಸರು',
      'phone_number': 'ಫೋನ್ ನಂಬರ್',
      'email': 'ಇಮೇಲ್',
      'save_basic_info': 'ಮೂಲ ಮಾಹಿತಿ ಉಳಿಸಿ',
      'no_driver_details': 'ಈ ಖಾತೆಗೆ ಯಾವುದೇ ಚಾಲಕ ವಿವರಗಳು ಕಂಡುಬಂದಿಲ್ಲ.',
      'order_status': 'ಆರ್ಡರ್ ಸ್ಥಿತಿ',
      'no_active_delivery': 'ಯಾವುದೇ ಸಕ್ರಿಯ ಡೆಲಿವರಿ ಇಲ್ಲ',
      'order_progress': 'ಆರ್ಡರ್ ಪ್ರಗತಿ',
      'profile_progress': 'ಪ್ರೊಫೈಲ್ ಪ್ರಗತಿ',
      'profile_complete': 'ಪ್ರೊಫೈಲ್ ಪೂರ್ಣಗೊಂಡಿದೆ',
      'all_done': 'ಎಲ್ಲವೂ ಪೂರ್ಣಗೊಂಡಿವೆ!',
      'steps_left': '{count} ಹಂತಗಳು ಬಾಕಿ',
      'tap_to_complete': 'ಪೂರ್ಣಗೊಳಿಸಲು ಟ್ಯಾಪ್ ಮಾಡಿ',
      'completed_steps': '{completed} / {total} ಹಂತಗಳು ಪೂರ್ಣಗೊಂಡಿವೆ',
      'pending': 'ಬಾಕಿ',
      'profile_completeness': 'ಪ್ರೊಫೈಲ್ ಪೂರ್ಣತೆ',
      'profile_basic_profile': 'ಮೂಲ ಪ್ರೊಫೈಲ್',
      'profile_basic_profile_desc': 'ಹೆಸರು, ಮೊಬೈಲ್ ಮತ್ತು ಇಮೇಲ್',
      'profile_photo': 'ಪ್ರೊಫೈಲ್ ಫೋಟೋ',
      'profile_photo_desc': 'ಪ್ರೊಫೈಲ್ ಫೋಟೋ ಸೇರಿಸಿ',
      'kyc_documents': 'KYC ದಾಖಲೆಗಳು',
      'kyc_documents_desc': 'ಐಡಿ ಪ್ರೂಫ್ ಮತ್ತು ಚಾಲನಾ ಪರವಾನಗಿ',
      'vehicle_details': 'ವಾಹನ ವಿವರಗಳು',
      'vehicle_details_desc': 'ನಿಮ್ಮ ವಾಹನವನ್ನು ನೋಂದಾಯಿಸಿ',
      'bank_account': 'ಬ್ಯಾಂಕ್ ಖಾತೆ',
      'bank_account_desc': 'ಪಾವತಿಗಳಿಗೆ ಬ್ಯಾಂಕ್ ಸೇರಿಸಿ',
      'delivery_zone': 'ಡೆಲಿವರಿ ವಲಯ',
      'delivery_zone_desc': 'ನಿಮ್ಮ ಕೆಲಸದ ಪ್ರದೇಶವನ್ನು ಆರಿಸಿ',
      'permissions': 'ಅನುಮತಿಗಳು',
      'permissions_desc': 'ಸ್ಥಳ ಮತ್ತು ಸೂಚನೆಗಳು',
      'not_submitted': 'ಸಲ್ಲಿಸಲಾಗಿಲ್ಲ',
      'accepted': 'ಸ್ವೀಕರಿಸಲಾಗಿದೆ',
      'rejected': 'ತಿರಸ್ಕರಿಸಲಾಗಿದೆ',
      'picked_up': 'ಪಿಕಪ್ ಮಾಡಲಾಗಿದೆ',
      'out_for_delivery': 'ಡೆಲಿವರಿಗೆ ಹೊರಟಿದೆ',
      'delivered': 'ವಿತರಿಸಲಾಗಿದೆ',
      'cancelled': 'ರದ್ದು ಮಾಡಲಾಗಿದೆ',
      'failed': 'ವಿಫಲವಾಗಿದೆ',
      'returned': 'ಹಿಂತಿರುಗಿಸಲಾಗಿದೆ',
      'draft': 'ಡ್ರಾಫ್ಟ್',
      'return_trip': 'ರಿಟರ್ನ್ ಟ್ರಿಪ್',
      'return_trip_note': 'ರಿಟರ್ನ್ ಟ್ರಿಪ್: {order_name}',
      'profile_complete_message': 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಪೂರ್ಣವಾಗಿದೆ! ನೀವು ಆನ್‌ಲೈನ್ ಆಗಲು ಸಿದ್ಧರಾಗಿದ್ದೀರಿ.',
      'profile_almost_complete_message': 'ಬಹುತೇಕ ಮುಗಿದಿದೆ! ಎಲ್ಲ ವೈಶಿಷ್ಟ್ಯಗಳನ್ನು ತೆರೆದುಕೊಳ್ಳಲು ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಅನ್ನು ಪೂರ್ಣಗೊಳಿಸಿ.',
      'profile_progress_message': 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ {completed}/{total} ಪೂರ್ಣವಾಗಿದೆ. ಮುಂದುವರಿಸಿ!',
      'profile_incomplete_message': 'ಡೆಲಿವರಿ ಆರಂಭಿಸಲು ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಅನ್ನು ಪೂರ್ಣಗೊಳಿಸಿ.',
      'submitted': 'ಸಲ್ಲಿಸಲಾಗಿದೆ',
      'unknown': 'ಅಜ್ಞಾತ',
      'trips_grouped_by_driver': 'ಡ್ರೈವರ್ ವಾರು ಟ್ರಿಪ್‌ಗಳು',
      'external_delivery_trip': 'ಬಾಹ್ಯ ಡೆಲಿವರಿ ಟ್ರಿಪ್',
      'external_delivery_trips': 'ಬಾಹ್ಯ ಡೆಲಿವರಿ ಟ್ರಿಪ್ಸ್',
      'delivery_failed': 'ಡೆಲಿವರಿ ವಿಫಲವಾಗಿದೆ',
      'confirm_failed_delivery': 'ವಿಫಲ ಡೆಲಿವರಿಯನ್ನು ದೃಢಪಡಿಸಿ',
      'add_any_additional_details': 'ಹೆಚ್ಚುವರಿ ವಿವರಗಳನ್ನು ಸೇರಿಸಿ...',
    },

    // ─── MALAYALAM ──────────────────────────────────────────────────────────
    'ml': {
      'cancel': 'റദ്ദാക്കുക',
      'save': 'സേവ് ചെയ്യുക',
      'retry': 'വീണ്ടും ശ്രമിക്കുക',
      'close': 'അടയ്ക്കുക',
      'continue': 'തുടരുക',
      'edit': 'തിരുത്തുക',
      'delete': 'ഇല്ലാതാക്കുക',
      'back': 'തിരിച്ചു',
      'loading': 'ലോഡ് ആകുന്നു...',
      'error': 'പിശക്',
      'select': 'തിരഞ്ഞെടുക്കുക',
      'change': 'മാറ്റുക',
      'upload': 'അപ്‌ലോഡ് ചെയ്യുക',
      'remove': 'നീക്കുക',
      'preview': 'മുന്നേ കാണുക',
      'open': 'തുറക്കുക',
      'saving': 'സേവ് ആകുന്നു...',
      'verified': 'സ്ഥിരീകരിച്ചു',
      'coming_soon': 'ഉടൻ വരുന്നു',
      'app_title': 'FlowFleet പാർട്ണർ',
      'delivery_partner': 'ഡെലിവറി പാർട്ണർ',
      'dashboard': 'ഡാഷ്‌ബോർഡ്',
      'availability': 'ലഭ്യത',
      'online_status': 'ഓൺലൈനിലാണ്, ഓർഡറുകൾ ലഭിക്കും',
      'offline_status': 'ഓഫ്‌ലൈൻ, പുതിയ ഓർഡറുകൾ ലഭിക്കില്ല',
      'kyc_warning': 'ഓൺലൈൻ ആകുന്നതിന് മുമ്പ് KYC + ബാങ്ക് + അനുമതികൾ പൂർത്തിയാക്കുക.',
      'complete': 'പൂർത്തിയാക്കുക',
      'earnings_summary': 'വരുമാന സംഗ്രഹം',
      'today': 'ഇന്ന്',
      'this_week': 'ഈ ആഴ്ച',
      'total': 'ആകെ',
      'pending_payout': 'കാത്തിരിക്കുന്ന പേമെന്റ്',
      'performance_metrics': 'പ്രകടന അളവുകൾ',
      'rating': 'റേറ്റിംഗ്',
      'acceptance': 'സ്വീകാര്യത',
      'completion': 'പൂർത്തീകരണം',
      'total_deliveries': 'ആകെ ഡെലിവറികൾ',
      'batch_pickup': 'ബാച്ച് പിക്കപ്',
      'multi_order_pickup': 'മൾട്ടി-ഓർഡർ പിക്കപ്',
      'pick_up_multiple': 'ഒരു യാത്രയിൽ ഒന്നിലധികം ഓർഡറുകൾ എടുക്കുക',
      'select_orders': 'ഓർഡറുകൾ തിരഞ്ഞെടുക്കുക',
      'view_trips': 'ട്രിപ്പുകൾ കാണുക',
      'available_deliveries': 'ലഭ്യമായ ഡെലിവറികൾ',
      'view_all': 'എല്ലാം കാണുക',
      'external_deliveries': 'ബാഹ്യ ഡെലിവറികൾ',
      'external_deliveries_desc': 'ERPNext-ൽ നിന്ന് ഡെലിവറികൾ കൈകാര്യം ചെയ്യുക',
      'view_deliveries': 'ഡെലിവറികൾ കാണുക',
      'active_order': 'സജീവ ഓർഡർ',
      'loading_active_order': 'സജീവ ഓർഡർ ലോഡ് ആകുന്നു...',
      'no_active_order': 'ഇപ്പോൾ സജീവ ഓർഡർ ഇല്ല.',
      'browse_nearby': 'പുതിയ ഓർഡറുകൾ കണ്ടെത്തുക',
      'add_another_order': 'മറ്റൊരു ഓർഡർ ചേർക്കുക',
      'notifications': 'അറിയിപ്പുകൾ',
      'no_notifications': 'ഇതുവരെ അറിയിപ്പുകൾ ഇല്ല.',
      'unable_load_notifications': 'അറിയിപ്പുകൾ ലോഡ് ചെയ്യാൻ കഴിഞ്ഞില്ല.',
      'quick_access': 'ദ്രുത ആക്സസ്',
      'my_profile': 'എന്റെ പ്രൊഫൈൽ',
      'earnings_history': 'വരുമാന ചരിത്രം',
      'documents': 'രേഖകൾ',
      'vehicle': 'വാഹനം',
      'bank_details': 'ബാങ്ക് വിവരങ്ങൾ',
      'orders_by_location': 'സ്ഥലം അനുസരിച്ച് ഓർഡറുകൾ',
      'available_orders': 'പുതിയ ഓർഡറുകൾ',
      'external_trips': 'ബാഹ്യ ട്രിപ്പുകൾ',
      'support': 'പിന്തുണ',
      'settings': 'ക്രമീകരണങ്ങൾ',
      'view_order': 'ഓർഡർ കാണുക',
      'navigate': 'നാവിഗേറ്റ് ചെയ്യുക',
      'open_maps': 'മാപ്പ് തുറക്കുക',
      'track_order': 'ഓർഡർ ട്രാക്ക് ചെയ്യുക',
      'mark_reached_pickup': 'പിക്കപ്പ് എത്തി',
      'mark_picked_up': 'എടുത്തു',
      'start_delivery': 'ഡെലിവറി ആരംഭിക്കുക',
      'mark_delivered': 'ഡെലിവർ ചെയ്തു',
      'order_delivered': 'ഓർഡർ ഡെലിവർ ആയി, വരുമാനം അപ്‌ഡേറ്റ് ആയി',
      'current_location': 'നിലവിലെ സ്ഥാനം',
      'location_not_selected': 'സ്ഥാനം ഇനിയും തിരഞ്ഞെടുത്തിട്ടില്ല',
      'unable_open_maps': 'Google Maps തുറക്കാൻ കഴിഞ്ഞില്ല',
      'login': 'ലോഗിൻ',
      'login_subtitle': 'തുടരാൻ മൊബൈൽ നമ്പർ നൽകുക',
      'mobile_number': 'മൊബൈൽ നമ്പർ',
      'enter_mobile': '10 അക്ക മൊബൈൽ നമ്പർ നൽകുക',
      'send_otp': 'OTP അയക്കുക',
      'sending_otp': 'OTP അയക്കുന്നു...',
      'otp': 'OTP',
      'change_number': 'നമ്പർ മാറ്റുക',
      'enter_otp': 'OTP നൽകുക',
      'resend_otp': 'OTP വീണ്ടും അയക്കുക',
      'verify_login': 'സ്ഥിരീകരിച്ച് ലോഗിൻ ചെയ്യുക',
      'verifying': 'സ്ഥിരീകരിക്കുന്നു...',
      'register': 'രജിസ്റ്റർ',
      'complete_registration': 'രജിസ്‌ട്രേഷൻ പൂർത്തിയാക്കുക',
      'register_subtitle': 'മൊബൈൽ സ്ഥിരീകരിച്ചു. വിവരങ്ങൾ നൽകുക.',
      'full_name': 'പൂർണ്ണ നാമം',
      'enter_full_name': 'നിങ്ങളുടെ പൂർണ്ണ നാമം നൽകുക',
      'email_optional': 'ഇമെയിൽ (ഐച്ഛികം)',
      'enter_email': 'ഇമെയിൽ വിലാസം നൽകുക',
      'create_account': 'അക്കൗണ്ട് സൃഷ്ടിക്കുക',
      'creating_account': 'അക്കൗണ്ട് സൃഷ്ടിക്കുന്നു...',
      'back_to_login': 'ലോഗിനിലേക്ക് തിരിച്ചു',
      'theme_customization': 'തീം ഇഷ്ടാനുസൃതമാക്കൽ',
      'theme_mode': 'തീം മോഡ്',
      'system': 'സിസ്റ്റം',
      'light': 'ലൈറ്റ്',
      'dark': 'ഡാർക്ക്',
      'background_color': 'പശ്ചാത്തല നിറം',
      'accent_color': 'ആക്സന്റ് നിറം',
      'language': 'ഭാഷ',
      'english': 'ഇംഗ്ലീഷ്',
      'hindi': 'ഹിന്ദി',
      'tamil': 'തമിഴ്',
      'telugu': 'തെലుగు',
      'kannada': 'ಕನ್ನಡ',
      'malayalam': 'മലയാളം',
      'bengali': 'ബംഗാളി',
      'ready_for_delivery_shifts': 'ഡെലിവറി ഷിഫ്റ്റുകൾക്ക് തയ്യാറാണ്',
      'reset_defaults': 'ഡിഫോൾട്ടിലേക്ക് പുനഃക്രമീകരിക്കുക',
      'reset_theme_title': 'തീം പുനഃക്രമീകരിക്കുക',
      'reset_theme_message': 'എല്ലാ തീം ക്രമീകരണങ്ങളും ഡിഫോൾട്ടിലേക്ക് പുനഃക്രമീകരിക്കണോ?',
      'reset': 'പുനഃക്രമീകരിക്കുക',
      'reset_success': 'തീം ഡിഫോൾട്ടിലേക്ക് പുനഃക്രമീകരിച്ചു',
      'navigation': 'നാവിഗേഷൻ',
      'route_summary': 'റൂട്ട് സംഗ്രഹം',
      'no_active_route': 'സജീവ റൂട്ട് ഇല്ല',
      'back_to_dashboard': 'ഡാഷ്‌ബോർഡിലേക്ക് തിരിച്ചു',
      'delivery_route': 'ഡെലിവറി റൂട്ട്',
      'pickup_store': 'പിക്കപ് സ്റ്റോർ',
      'delivery_drop': 'ഡെലിവറി ഡ്രോപ്',
      'open_google_maps': 'Google Maps-ൽ തുറക്കുക',
      'use_inapp_nav': 'ഇൻ-ആപ്പ് നാവിഗേഷൻ ഉപയോഗിക്കുക',
      'reached_pickup': 'പിക്കപ്പ് എത്തി',
      'choose_language': 'ഭാഷ തിരഞ്ഞെടുക്കുക',
      'choose_language_subtitle': 'ദൈനംദിന ഉപയോഗത്തിനുള്ള ഭാഷ തിരഞ്ഞെടുക്കുക',
      'language_info': 'ഈ ആപ്പ് ബഹുഭാഷ പിന്തുണ നൽകുന്നു. ക്രമീകരണങ്ങളിൽ എപ്പോഴും ഭാഷ മാറ്റാം.',
      'my_profile_title': 'എന്റെ പ്രൊഫൈൽ',
      'driver_account': 'ഡ്രൈവർ അക്കൗണ്ട്',
      'basic_information': 'അടിസ്ഥാന വിവരങ്ങൾ',
      'edit_profile_desc': 'പേര്, ഫോൺ, ഇമെയിൽ, പ്രൊഫൈൽ ചിത്രം തിരുത്തുക',
      'name': 'പേര്',
      'phone_number': 'ഫോൺ നമ്പർ',
      'email': 'ഇമെയിൽ',
      'save_basic_info': 'അടിസ്ഥാന വിവരങ്ങൾ സേവ് ചെയ്യുക',
      'no_driver_details': 'ഈ അക്കൗണ്ടിന് ഡ്രൈവർ വിവരങ്ങൾ കണ്ടെത്തിയില്ല.',
      'order_status': 'ഓർഡർ സ്ഥിതി',
      'no_active_delivery': 'സജീവ ഡെലിവറി ഇല്ല',
      'order_progress': 'ഓർഡർ പുരോഗതി',
      'profile_progress': 'പ്രൊഫൈൽ പുരോഗതി',
      'profile_complete': 'പ്രൊഫൈൽ പൂർത്തിയായി',
      'all_done': 'എല്ലാം പൂർത്തിയായി!',
      'steps_left': '{count} ഘട്ടങ്ങൾ ബാക്കി',
      'tap_to_complete': 'പൂർത്തിയാക്കാൻ തൊടുക',
      'completed_steps': '{completed} / {total} ഘട്ടങ്ങൾ പൂർത്തിയായി',
      'pending': 'തീർപ്പാക്കാത്തത്',
      'profile_completeness': 'പ്രൊഫൈൽ പൂർത്തിത്വം',
      'profile_basic_profile': 'അടിസ്ഥാന പ്രൊഫൈൽ',
      'profile_basic_profile_desc': 'പേര്, മൊബൈൽ & ഇമെയിൽ',
      'profile_photo': 'പ്രൊഫൈൽ ഫോട്ടോ',
      'profile_photo_desc': 'പ്രൊഫൈൽ ഫോട്ടോ ചേർക്കുക',
      'kyc_documents': 'KYC രേഖകൾ',
      'kyc_documents_desc': 'ഐഡി തെളിവ് & ഡ്രൈവിംഗ് ലൈസൻസ്',
      'vehicle_details': 'വാഹന വിശദാംശങ്ങൾ',
      'vehicle_details_desc': 'നിങ്ങളുടെ വാഹനം രജിസ്റ്റർ ചെയ്യുക',
      'bank_account': 'ബാങ്ക് അക്കൗണ്ട്',
      'bank_account_desc': 'പേയൗട്ടുകൾക്കായി ബാങ്ക് ചേർക്കുക',
      'delivery_zone': 'ഡെലിവറി മേഖല',
      'delivery_zone_desc': 'നിങ്ങളുടെ പ്രവർത്തന പ്രദേശം തിരഞ്ഞെടുക്കുക',
      'permissions': 'അനുമതികൾ',
      'permissions_desc': 'സ്ഥാനം & അറിയിപ്പുകൾ',
      'not_submitted': 'സമർപ്പിച്ചിട്ടില്ല',
      'accepted': 'സ്വീകരിച്ചു',
      'rejected': 'നിരസിച്ചു',
      'picked_up': 'എടുത്തു',
      'out_for_delivery': 'ഡെലിവറിക്ക് പുറപ്പെട്ടു',
      'delivered': 'വിതരിച്ചു',
      'cancelled': 'റദ്ദാക്കി',
      'failed': 'പരാജയപ്പെട്ടു',
      'returned': 'തിരികെ നൽകി',
      'draft': 'ഡ്രാഫ്റ്റ്',
      'return_trip': 'റിട്ടേൺ ട്രിപ്പ്',
      'return_trip_note': 'റിട്ടേൺ ട്രിപ്പ്: {order_name}',
      'profile_complete_message': 'നിങ്ങളുടെ പ്രൊഫൈൽ പൂർത്തിയായി! നിങ്ങൾ ഓൺലൈനായി പോകാൻ തയ്യാറാണ്.',
      'profile_almost_complete_message': 'ഇനി കുറച്ചു മാത്രം! എല്ലാം തുറക്കാൻ പ്രൊഫൈൽ പൂർത്തിയാക്കുക.',
      'profile_progress_message': 'നിങ്ങളുടെ പ്രൊഫൈൽ {completed}/{total} പൂർത്തിയായി. തുടരുക!',
      'profile_incomplete_message': 'ഡെലിവറി തുടങ്ങാൻ പ്രൊഫൈൽ പൂർത്തിയാക്കുക.',
      'submitted': 'സമർപ്പിച്ചു',
      'unknown': 'അജ്ഞാതം',
      'trips_grouped_by_driver': 'ഡ്രൈവർ തിരിച്ചുള്ള ട്രിപ്പുകൾ',
      'external_delivery_trip': 'ബാഹ്യ ഡെലിവറി ട്രിപ്പ്',
      'external_delivery_trips': 'ബാഹ്യ ഡെലിവറി ട്രിപ്പുകൾ',
      'delivery_failed': 'ഡെലിവറി പരാജയപ്പെട്ടു',
      'confirm_failed_delivery': 'പരാജയപ്പെട്ട ഡെലിവറി സ്ഥിരീകരിക്കുക',
      'add_any_additional_details': 'കൂടുതൽ വിശദാംശങ്ങൾ ചേർക്കുക...',
    },

    // ─── BENGALI ────────────────────────────────────────────────────────────
    'bn': {
      'cancel': 'বাতিল',
      'save': 'সংরক্ষণ',
      'retry': 'আবার চেষ্টা',
      'close': 'বন্ধ করুন',
      'continue': 'চালিয়ে যান',
      'edit': 'সম্পাদনা',
      'delete': 'মুছুন',
      'back': 'পেছনে',
      'loading': 'লোড হচ্ছে...',
      'error': 'ত্রুটি',
      'select': 'নির্বাচন করুন',
      'change': 'পরিবর্তন করুন',
      'upload': 'আপলোড',
      'remove': 'সরান',
      'preview': 'প্রিভিউ',
      'open': 'খুলুন',
      'saving': 'সংরক্ষণ হচ্ছে...',
      'verified': 'যাচাইকৃত',
      'coming_soon': 'শীঘ্রই আসছে',
      'app_title': 'FlowFleet পার্টনার',
      'delivery_partner': 'ডেলিভারি পার্টনার',
      'dashboard': 'ড্যাশবোর্ড',
      'availability': 'প্রাপ্যতা',
      'online_status': 'অনলাইনে আছেন, অর্ডার পাচ্ছেন',
      'offline_status': 'অফলাইন, নতুন অর্ডার আসবে না',
      'kyc_warning': 'অনলাইনে যাওয়ার আগে KYC + ব্যাংক + অনুমতি সম্পন্ন করুন।',
      'complete': 'সম্পন্ন করুন',
      'earnings_summary': 'আয় সারসংক্ষেপ',
      'today': 'আজ',
      'this_week': 'এই সপ্তাহ',
      'total': 'মোট',
      'pending_payout': 'বকেয়া পেমেন্ট',
      'performance_metrics': 'পারফরম্যান্স মেট্রিক্স',
      'rating': 'রেটিং',
      'acceptance': 'গ্রহণযোগ্যতা',
      'completion': 'সমাপ্তি',
      'total_deliveries': 'মোট ডেলিভারি',
      'batch_pickup': 'ব্যাচ পিকআপ',
      'multi_order_pickup': 'মাল্টি-অর্ডার পিকআপ',
      'pick_up_multiple': 'এক ট্রিপে একাধিক অর্ডার তুলুন',
      'select_orders': 'অর্ডার নির্বাচন করুন',
      'view_trips': 'ট্রিপ দেখুন',
      'available_deliveries': 'উপলব্ধ ডেলিভারি',
      'view_all': 'সব দেখুন',
      'external_deliveries': 'বাহ্যিক ডেলিভারি',
      'external_deliveries_desc': 'ERPNext থেকে ডেলিভারি পরিচালনা করুন',
      'view_deliveries': 'ডেলিভারি দেখুন',
      'active_order': 'সক্রিয় অর্ডার',
      'loading_active_order': 'সক্রিয় অর্ডার লোড হচ্ছে...',
      'no_active_order': 'এখন কোনো সক্রিয় অর্ডার নেই।',
      'browse_nearby': 'নতুন অর্ডার খুঁজুন',
      'add_another_order': 'আরেকটি অর্ডার যোগ করুন',
      'notifications': 'বিজ্ঞপ্তি',
      'no_notifications': 'এখনও কোনো বিজ্ঞপ্তি নেই।',
      'unable_load_notifications': 'বিজ্ঞপ্তি লোড করা যায়নি।',
      'quick_access': 'দ্রুত অ্যাক্সেস',
      'my_profile': 'আমার প্রোফাইল',
      'earnings_history': 'আয়ের ইতিহাস',
      'documents': 'নথিপত্র',
      'vehicle': 'যানবাহন',
      'bank_details': 'ব্যাংক বিবরণ',
      'orders_by_location': 'অবস্থান অনুযায়ী অর্ডার',
      'available_orders': 'নতুন অর্ডার',
      'external_trips': 'বাহ্যিক ট্রিপ',
      'support': 'সহায়তা',
      'settings': 'সেটিংস',
      'view_order': 'অর্ডার দেখুন',
      'navigate': 'নেভিগেট করুন',
      'open_maps': 'মানচিত্র খুলুন',
      'track_order': 'অর্ডার ট্র্যাক করুন',
      'mark_reached_pickup': 'পিকআপে পৌঁছেছি',
      'mark_picked_up': 'তুলেছি',
      'start_delivery': 'ডেলিভারি শুরু করুন',
      'mark_delivered': 'ডেলিভারি করা হয়েছে',
      'order_delivered': 'অর্ডার ডেলিভার হয়েছে, আয় আপডেট হয়েছে',
      'current_location': 'বর্তমান অবস্থান',
      'location_not_selected': 'অবস্থান এখনও নির্বাচন করা হয়নি',
      'unable_open_maps': 'Google Maps খুলতে পারেনি',
      'login': 'লগিন',
      'login_subtitle': 'চালিয়ে যেতে মোবাইল নম্বর দিন',
      'mobile_number': 'মোবাইল নম্বর',
      'enter_mobile': '১০ সংখ্যার মোবাইল নম্বর দিন',
      'send_otp': 'OTP পাঠান',
      'sending_otp': 'OTP পাঠানো হচ্ছে...',
      'otp': 'OTP',
      'change_number': 'নম্বর পরিবর্তন করুন',
      'enter_otp': 'OTP দিন',
      'resend_otp': 'OTP আবার পাঠান',
      'verify_login': 'যাচাই করে লগিন করুন',
      'verifying': 'যাচাই হচ্ছে...',
      'register': 'নিবন্ধন',
      'complete_registration': 'নিবন্ধন সম্পন্ন করুন',
      'register_subtitle': 'মোবাইল যাচাই হয়েছে। বিবরণ পূরণ করুন।',
      'full_name': 'পুরো নাম',
      'enter_full_name': 'আপনার পুরো নাম দিন',
      'email_optional': 'ইমেইল (ঐচ্ছিক)',
      'enter_email': 'ইমেইল ঠিকানা দিন',
      'create_account': 'অ্যাকাউন্ট তৈরি করুন',
      'creating_account': 'অ্যাকাউন্ট তৈরি হচ্ছে...',
      'back_to_login': 'লগিনে ফিরে যান',
      'theme_customization': 'থিম কাস্টমাইজেশন',
      'theme_mode': 'থিম মোড',
      'system': 'সিস্টেম',
      'light': 'লাইট',
      'dark': 'ডার্ক',
      'background_color': 'ব্যাকগ্রাউন্ড রং',
      'accent_color': 'অ্যাকসেন্ট রং',
      'language': 'ভাষা',
      'english': 'ইংরেজি',
      'hindi': 'হিন্দি',
      'tamil': 'তামিল',
      'telugu': 'তেলুগু',
      'kannada': 'কন্নড়',
      'malayalam': 'মালায়ালাম',
      'bengali': 'বাংলা',
      'ready_for_delivery_shifts': 'ডেলিভারি শিফটের জন্য প্রস্তুত',
      'reset_defaults': 'ডিফল্টে রিসেট করুন',
      'reset_theme_title': 'থিম রিসেট করুন',
      'reset_theme_message': 'সমস্ত থিম সেটিংস ডিফল্টে রিসেট করবেন?',
      'reset': 'রিসেট',
      'reset_success': 'থিম ডিফল্টে রিসেট হয়েছে',
      'navigation': 'নেভিগেশন',
      'route_summary': 'রুট সারসংক্ষেপ',
      'no_active_route': 'কোনো সক্রিয় রুট নেই',
      'back_to_dashboard': 'ড্যাশবোর্ডে ফিরে যান',
      'delivery_route': 'ডেলিভারি রুট',
      'pickup_store': 'পিকআপ স্টোর',
      'delivery_drop': 'ডেলিভারি ড্রপ',
      'open_google_maps': 'Google Maps এ খুলুন',
      'use_inapp_nav': 'ইন-অ্যাপ নেভিগেশন ব্যবহার করুন',
      'reached_pickup': 'পিকআপে পৌঁছেছি',
      'choose_language': 'ভাষা বেছে নিন',
      'choose_language_subtitle': 'দৈনন্দিন ব্যবহারের জন্য পছন্দের ভাষা নির্বাচন করুন',
      'language_info':
          'এই অ্যাপটি বহুভাষিক সমর্থন করে। সেটিংস থেকে যেকোনো সময় ভাষা পরিবর্তন করা যাবে।',
      'my_profile_title': 'আমার প্রোফাইল',
      'driver_account': 'ড্রাইভার অ্যাকাউন্ট',
      'basic_information': 'মৌলিক তথ্য',
      'edit_profile_desc': 'নাম, ফোন, ইমেইল এবং প্রোফাইল ছবি সম্পাদনা করুন',
      'name': 'নাম',
      'phone_number': 'ফোন নম্বর',
      'email': 'ইমেইল',
      'save_basic_info': 'মৌলিক তথ্য সংরক্ষণ করুন',
      'no_driver_details': 'এই অ্যাকাউন্টের জন্য কোনো ড্রাইভার বিবরণ পাওয়া যায়নি।',
      'order_status': 'অর্ডার স্ট্যাটাস',
      'no_active_delivery': 'কোনো সক্রিয় ডেলিভারি নেই',
      'order_progress': 'অর্ডার অগ্রগতি',
      'profile_progress': 'প্রোফাইল অগ্রগতি',
      'profile_complete': 'প্রোফাইল সম্পূর্ণ',
      'all_done': 'সব সম্পন্ন!',
      'steps_left': '{count} ধাপ বাকি',
      'tap_to_complete': 'সম্পূর্ণ করতে ট্যাপ করুন',
      'completed_steps': '{completed} এর মধ্যে {total} ধাপ সম্পন্ন',
      'pending': 'মুলতুবি',
      'profile_completeness': 'প্রোফাইল সম্পূর্ণতা',
      'profile_basic_profile': 'মৌলিক প্রোফাইল',
      'profile_basic_profile_desc': 'নাম, মোবাইল ও ইমেইল',
      'profile_photo': 'প্রোফাইল ছবি',
      'profile_photo_desc': 'একটি প্রোফাইল ছবি যোগ করুন',
      'kyc_documents': 'KYC নথি',
      'kyc_documents_desc': 'আইডি প্রুফ ও ড্রাইভিং লাইসেন্স',
      'vehicle_details': 'যানবাহনের বিবরণ',
      'vehicle_details_desc': 'আপনার যানবাহন নিবন্ধন করুন',
      'bank_account': 'ব্যাংক অ্যাকাউন্ট',
      'bank_account_desc': 'পেআউটের জন্য ব্যাংক যোগ করুন',
      'delivery_zone': 'ডেলিভারি জোন',
      'delivery_zone_desc': 'আপনার কাজের এলাকা নির্বাচন করুন',
      'permissions': 'অনুমতি',
      'permissions_desc': 'অবস্থান ও নোটিফিকেশন',
      'not_submitted': 'জমা দেওয়া হয়নি',
      'accepted': 'গৃহীত',
      'rejected': 'প্রত্যাখ্যাত',
      'picked_up': 'নেওয়া হয়েছে',
      'out_for_delivery': 'ডেলিভারির জন্য বের হয়েছে',
      'delivered': 'ডেলিভার হয়েছে',
      'cancelled': 'বাতিল',
      'failed': 'ব্যর্থ',
      'returned': 'ফেরত দেওয়া হয়েছে',
      'draft': 'খসড়া',
      'return_trip': 'ফেরত যাত্রা',
      'return_trip_note': 'ফেরত যাত্রা: {order_name}',
      'profile_complete_message': 'আপনার প্রোফাইল সম্পূর্ণ! আপনি অনলাইনে যাওয়ার জন্য প্রস্তুত।',
      'profile_almost_complete_message': 'আরও একটু! সব বৈশিষ্ট্য আনলক করতে প্রোফাইল সম্পূর্ণ করুন।',
      'profile_progress_message': 'আপনার প্রোফাইল {completed}/{total} সম্পূর্ণ। এগিয়ে যান!',
      'profile_incomplete_message': 'ডেলিভারি শুরু করতে আপনার প্রোফাইল সম্পূর্ণ করুন।',
      'submitted': 'জমা দেওয়া হয়েছে',
      'unknown': 'অজানা',
      'trips_grouped_by_driver': 'ড্রাইভার অনুযায়ী ট্রিপ',
      'external_delivery_trip': 'বাহ্যিক ডেলিভারি ট্রিপ',
      'external_delivery_trips': 'বাহ্যিক ডেলিভারি ট্রিপসমূহ',
      'delivery_failed': 'ডেলিভারি ব্যর্থ',
      'confirm_failed_delivery': 'ব্যর্থ ডেলিভারি নিশ্চিত করুন',
      'add_any_additional_details': 'অতিরিক্ত বিবরণ যোগ করুন...',
    },
  };

  static String get(String languageCode, String key) {
    final String lang = isSupportedLanguageCode(languageCode)
        ? languageCode
        : 'en';
    return _dict[lang]?[key] ?? _dict['en']?[key] ?? key;
  }

  static String format(
    String languageCode,
    String key, [
    Map<String, String> params = const <String, String>{},
  ]) {
    String value = get(languageCode, key);
    params.forEach((placeholder, replacement) {
      value = value.replaceAll('{$placeholder}', replacement);
    });
    return value;
  }

  static bool isSupportedLanguageCode(String languageCode) {
    return _dict.containsKey(languageCode);
  }
}
